### ISSUE TITLE
Probably just me, but unable to download January 2024 LFS PUMP file

### ISSUE THREAD

**Issue by aaa19566** [mountainMath/canpumf#7]
Getting this error: 

"2024-01 is not available, check available LFS PUMF versions via `list_available_lfs_pumf_versions()`" even though 2024-01 is in the list of available versions.

**Comment by mountainMath** [comment]
Looks like a coding error on the [StatCan website](https://www150.statcan.gc.ca/n1/pub/71m0001x/71m0001x2021001-eng.htm). Their embedded metadata labels it as January 2023, and that's what the package parses when  
<img width="584" alt="image" src="https://github.com/mountainMath/canpumf/assets/1395960/6bd0e87b-bb09-4328-b44b-59d7dcab706e">

I will reach out to StatCan to get that fixed, meanwhile I implemented a manual quick-fix, it should work after you reinstall the package with
```
remotes::install_github("mountainmath/canpumf")
```

**Comment by aaa19566** [comment]
Thanks! Glad it wasn't me. :)

**Comment by mountainMath** [comment]
This has been fixed on the StatCan website too now.
